name: Trigger another workflow on pull request review

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check if all reviews are approved
        id: check-reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pull_request_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          repository=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")
          requested_reviewers=$(curl -s -H "Authorization: $GITHUB_TOKEN" "https://api.github.com/repos/$repository/pulls/$pull_request_number/requested_reviewers")
          review_count=$(echo "$requested_reviewers" | jq '.users | length')

          if [ review_count -eq 0 ]; then
            echo 'No reviews found.'
            exit 1
          fi

          reviews=$(curl -s -H "Authorization: $GITHUB_TOKEN" "https://api.github.com/repos/$repository/pulls/$pull_request_number/reviews")
          approved_review_count=$(echo "$reviews" | jq 'map(select(.state == "APPROVED")) | length')
          if [ $review_count -eq $approved_review_count ]; then
            echo 'All reviews are approved.'
            # Trigger another workflow
            echo "::set-output name=all_reviews_approved::true"
          else
            echo 'Not all reviews are approved.'
            exit 1
          fi
